server:
  port: 8081

spring:
  flyway:
    enabled: false
  application:
    name: user-service
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    url: jdbc:postgresql://gaurav-database-instance.cyzc7olnurqo.ap-south-1.rds.amazonaws.com:5432/octa_user_service_db?createDatabaseIfNotExist=true
    password: Hexa1234
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true
